default: &default
  adapter: mysql2
  encoding: utf8
  database: project_management_dev
  username: root
  password: root
  host: localhost

development:
  <<: *default

production:
  adapter: postgresql
  encoding: unicode
